### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by vade** [vladan-stojnic/Detection-of-Flying-Honeybees-in-UAV-Videos#1]
Hello

Just curious what if any license is intended with this project. Thank you in advance for sharing the project and the work!

**Comment by vladan-stojnic** [comment]
Sorry for an extremely late response, [MIT license](https://github.com/vladan-stojnic/Detection-of-Small-Flying-Objects-in-UAV-Videos/blob/main/LICENSE) has been added to the project.
