### ISSUE TITLE
Error in HDF5 dataset creation

### ISSUE THREAD

**Issue by msmcfarlin** [vladan-stojnic/Detection-of-Flying-Honeybees-in-UAV-Videos#4]
Hi,

Thank you for the thorough paper and sharing your code, I think this code could be very useful in my own work detecting distant birds. I've been trying to work through your code before trying it on my own data though I have some questions and have run into some difficulties. I'm using the files available at https://zenodo.org/record/4400651. 

I stabilized the videos with the initial `stabilization.py` then generated synthetic honeybees. 

`python add_bees_to_video.py -i workspace/background_stabilized/ -o workspace/bees_added/ --mask workspace/mask/ --bee_mean 0.25 --num_synthetic_videos 3`

One question on the bee command, what is the mask directory? I see that files are generated during that process.

After running `add_bees_to_video.py`, 3 MP4 files are generated in the "bees_added" directory and 3 videos in the "mask" directory though I cannot open any of these files in a media player. When I input a synthetic bee file into the `bgsub.py` command, the output looks as I would expect though, with small dots moving through the frame. 

`python Detection-of-Small-Flying-Objects/bgsub.py -i workspace/bees_added/Out_1.MP4 -o workspace/background_sub/background_sub1.MP4 --num_avg 20`

It is extremely grainy for the last 3 seconds of video. I tried adjusting the `--num_avg` value between 10-100 and found that 20 appeared to reduce the graininess though what value did you use in your work?

My main error came when I moved to HDF5 dataset creation...

`python chunked_dataset.py -i workspace/background_sub/ --mask workspace/mask/ -o workspace/HDF5/ --type 'train'`

Error...

              Traceback (most recent call last):
                File "Detection-of-Small-Flying-Objects/chunked_dataset.py", line 174, in <module>
                  os.path.join(MASKS_PATH, '/Mask_' + str(vid)+'.MP4'), cnt)
                File "Detection-of-Small-Flying-Objects/chunked_dataset.py", line 117, in extract_data
                  bgsub = rgb2gray(vread(bgsub_path))
                File "/home/arc/miniconda3/envs/bee4exp/lib/python3.6/site-packages/skvideo/io/io.py", line 144, in vread
                  reader = FFmpegReader(fname, inputdict=inputdict, outputdict=outputdict, verbosity=verbosity)
                File "/home/arc/miniconda3/envs/bee4exp/lib/python3.6/site-packages/skvideo/io/ffmpeg.py", line 88, in __init__
                  self.size = os.path.getsize(filename)
                File "/home/arc/miniconda3/envs/bee4exp/lib/python3.6/genericpath.py", line 50, in getsize
                  return os.stat(filename).st_size
              FileNotFoundError: [Errno 2] No such file or directory: 'workspace/background_sub/Out_522.MP4'

I see that the command is trying to use file Out_522.MP4 in the background_sub directory though that obviously doesn't exist. Do you have any idea why the command is trying to use Out_522.MP4 and not one of the other files in the directory?

Thank you for your time!

-Mike

**Comment by vladan-stojnic** [comment]
Hi,

For the number of frames to be averaged we used 50. All the values that we used in the paper should be default ones in argument parser.

As for the HDF5 dataset creating, that script is sadly made to work with the number of synthetic videos that we used in our paper (1000) and it will not work if the number of videos is smaller. However, it should be relatively easy to change that. You need to change the line `vids = np.arange(1, 1001)` to something like `vids = np.arange(1, 4)` (for you case of 3 synthetic videos). And then change lines (that were used to select 500 videos for training, 250 for validation, and 250 for testing)
```
if TYPE == 'val':
    div = 250
    offset = 500
elif TYPE == 'test':
    div = 250
    offset = 750
else:
    div = 500
    offset = 0
```
to something that will split those 3 videos into the ones that will be used for training, validation and testing. Those two changes should do it. I don't have time now to try it and maybe make it work by checking how many videos exist and make some reasonable split to train/val/test. 

Also it might be worth changing how many samples per class (number of bees in the middle frame) to select when number of synthetic videos is soo small. Those are the lines
```
if TYPE == 'val' or TYPE == 'test':
    MAX_CLASS = 3200
else:
    MAX_CLASS = 13440
```

**Comment by msmcfarlin** [comment]
Thank you for the code! That was really helpful. I've got the HDF5 dataset creation script running.

Out of curiosity, do you recall the computer hardware you used to run the dataset in the paper? This is my first time working with this type of code and video files and I don't have a sense of the CPU/RAM/VRAM requirements for a project like this.

**Comment by vladan-stojnic** [comment]
If I remember correctly hardware was something like:

CPU: Intel i7-8700K
RAM: 64GB
GPU: 2 x 1080ti (11GB)

It should be possible to run it even on something less powerful, but you might need to use smaller batch size if smaller amount of VRAM is available.
