### ISSUE TITLE
image input

### ISSUE THREAD

**Issue by mahilaMoghadami** [vladan-stojnic/Detection-of-Flying-Honeybees-in-UAV-Videos#5]
Hi
how can I train and use this repository just with image and text annotations as dataset? (don't access to input video file)
is it possible or not?
thank you.

**Comment by vladan-stojnic** [comment]
Hi,

I am not sure what exactly you want to do, but this method was developed specifically for videos (even a specific type of videos). So I would say that it is not possible to use, at least not without knowing what is the target task.
