### ISSUE TITLE
Missing test video?

### ISSUE THREAD

**Issue by tze-min** [vladan-stojnic/Detection-of-Flying-Honeybees-in-UAV-Videos#6]
Hi! I came across your paper on Papers with Code, and was taking a look at the [BEE4EXP dataset on Zenodo](https://zenodo.org/record/4400651#.Y0-o2nZBxnI). 

`test_seq3.mp4` seems to be missing from the list of downloadable files. Is that meant to be the case?

![image](https://user-images.githubusercontent.com/69795629/196627941-c0f7da3d-a0b0-4fc5-8f2b-86a35df128bc.png)

**Comment by vladan-stojnic** [comment]
Sorry for the late replay. The file was missing by mistake. It should be available for download now [here](https://doi.org/10.5281/zenodo.4400650).

**Comment by tze-min** [comment]
Cool, thanks a lot!
