### ISSUE TITLE
chunked_dataset script error

### ISSUE THREAD

**Issue by msmcfarlin** [vladan-stojnic/Detection-of-Flying-Honeybees-in-UAV-Videos#7]
Hello,

I am having troubling running the HDF5 dataset creation part of the tutorial. I modified the chunked_dataset.py script as you suggested in #4 to run with 3 input videos. When I run the code... 

`python Detection-of-Small-Flying-Objects/chunked_dataset_modified.py -i bee_workspace/background_sub --mask bee_workspace/mask_test --num_synthetic_videos 3 -o bee_workspace/HDF5 --type 'train'`

...there is a warning output that reads...

> /home/user/.conda/envs/bee4exp/lib/python3.6/site-packages/skimage/transform/_warps.py:24: UserWarning: The default multichannel argument (None) is deprecated.  Please specify either True or False explicitly.  multichannel will default to False starting with release 0.16.
>   warn('The default multichannel argument (None) is deprecated.  Please '
> /home/user/.conda/envs/bee4exp/lib/python3.6/site-packages/skimage/transform/_warps.py:105: UserWarning: The default mode, 'constant', will be changed to 'reflect' in skimage 0.15.
>   warn("The default mode, 'constant', will be changed to 'reflect' in "

I'm not quite sure how to interpret this error, do you have any thoughts?

Thank you for your time.
-Mike

**Comment by vladan-stojnic** [comment]
Hi,

Both of these are only warnings from scikit-image about changing the default behaviour in newer versions of the library. You should be fine with just ignoring these. 

Best,
Vladan
