### ISSUE TITLE
Using test/npy files, and object annotation

### ISSUE THREAD

**Issue by msmcfarlin** [vladan-stojnic/Detection-of-Flying-Honeybees-in-UAV-Videos#8]
Hello,

Apologies for all the questions! I am still getting used to running this type of workflow, thank you for all the assistance so far.

I downloaded all of the files from zenodo but during what steps should I be using the `test_seq*.mp4` and `test_seq*.npy` files?

Thank you so much for your help!

-Mike

**Comment by msmcfarlin** [comment]
After going back through your publication, I realized that the `test_seq*.mp4` files were used in a subsequent round of object detection, and that the `test_seq*.npy` files were used to evaluate the model detection against the human label annotations of detections.

In the publication you mention that you developed a tool for manually labeling small moving objects, where you could move through a video frame by frame and mark the location of target objects. Is this available online?

Thank you.

**Comment by vladan-stojnic** [comment]
Hi,

You found the correct answer for files (they were used for evaluation). As for the labelling tool, it is available in this repository in `annotate.py` file. Explanation of command line argument to run the script is given in the file, while commands to move through the video and annotate will be printed in the terminal when you run the script.
